### ISSUE TITLE
Bug in encode_images.py

### ISSUE THREAD

**Issue by florian-hoenicke** [rolux/stylegan2encoder#12]
Hi,
I just ran the following command and got an error:

python encode_images.py aligned_images/ generated_images/ latent_representations/

Traceback (most recent call last):
  File "encode_images.py", line 79, in <module>
    main()
  File "encode_images.py", line 52, in main
    generator = Generator(Gs_network, args.batch_size, randomize_noise=args.randomize_noise)
  File "/home/hoenicke_florian/stylegan2encoder/encoder/generator_model.py", line 35, in __init__
    self.generator_output = self.graph.get_tensor_by_name('G_synthesis_1/_Run/concat:0')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/ops.py", line 3783, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/ops.py", line 3607, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/ops.py", line 3649, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'G_synthesis_1/_Run/concat:0' refers to a Tensor which does not exist. The operation, 'G_synthesis_1/_Run/concat', does not exist in the graph."

**Comment by sandhyalaxmiK** [comment]
install tensorflow-gpu with version 1.14. Not 1.15

**Comment by florian-hoenicke** [comment]
Thanks a lot :)
