### ISSUE TITLE
Bug in encoder

### ISSUE THREAD

**Issue by florian-hoenicke** [rolux/stylegan2encoder#13]
When I run the following command, I get an error:
python project_images.py aligned_images/ generated_images/

Traceback (most recent call last):
  File "project_images.py", line 121, in <module>
    main()
  File "project_images.py", line 107, in main
    proj.set_network(Gs)
  File "/home/hoenicke_florian/stylegan2encoder/projector.py", line 117, in set_network
    self._lpips = misc.load_pkl(self.vgg16_pkl) # vgg16_zhang_perceptual.pkl
  File "/home/hoenicke_florian/stylegan2encoder/training/misc.py", line 26, in load_pkl
    with open_file_or_url(file_or_url) as file:
  File "/home/hoenicke_florian/stylegan2encoder/training/misc.py", line 22, in open_file_or_url
    return dnnlib.util.open_url(file_or_url, cache_dir='.stylegan2-cache')
  File "/home/hoenicke_florian/stylegan2encoder/dnnlib/util.py", line 383, in open_url
    raise IOError("Google Drive download quota exceeded -- please try again later")
OSError: Google Drive download quota exceeded -- please try again later

**Comment by sandhyalaxmiK** [comment]
Download vgg16_pkl (vgg16_zhang_perceptual.pkl) from this link 
https://drive.google.com/uc?id=1N2-m9qszOeVC9Tq77WxsLnuWwOedQiD2   
and save it in networks directory.
In project_images.py, replace --vgg16-pkl argument path from "https://drive.google.com/uc?id=1N2-m9qszOeVC9Tq77WxsLnuWwOedQiD2" to  "networks/vgg16_zhang_perceptual.pkl".
